# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Cypress test run

on: 
  push:
    branches: 
      - main

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
    - uses: actions/checkout@v2

    - name: Cypress run
    - uses: cypress-io/github-action@v2
    - run: cypress run
      timeout-minutes: 10
      with:
        browser: chrome
        headless: true
    
 
